-- 人物中世纪收藏卡（采购×2、老板×4）。可重复执行。不覆盖已有卡面。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 154, 'P-19', '盐引官', 2, 'purchase', 1, 'support', '本回合员工调用机会 +1，并为一名玩家增加 2 点防御', '/images/cards/采购_盐引官.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-19');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_ACTION_POINTS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-19' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'ADD_ACTION_POINTS');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-19' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'ADD_SHIELD');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 155, 'P-20', '皮货采买', 2, 'purchase', 2, 'defend', '抽 1 张牌，本回合霸凌者攻击 -1，并为自己增加 2 点防御', '/images/cards/采购_皮货采买.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-20');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-20' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'DRAW_CARDS');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-20' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'REDUCE_BOSS_ATTACK');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 3, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-20' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 3 AND e.effect_type = 'ADD_SHIELD');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 156, 'B-04', '东家', 3, 'public', 2, 'support', '双方各恢复 2 点血量，本回合霸凌者攻击 -1', '/images/cards/老板_东家.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-04');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-04' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'HEAL_PLAYER');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-04' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'REDUCE_BOSS_ATTACK');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 157, 'B-05', '矿主', 3, 'public', 3, 'attack', '立即造成 3 点伤害，下回合再造成 2 点伤害', '/images/cards/老板_矿主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-05');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-05' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'DAMAGE_BOSS');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-05' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'DAMAGE_BOSS');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 158, 'B-06', '猎场主', 3, 'public', 2, 'attack', '立即造成 2 点伤害，并为双方各增加 1 点调用机会', '/images/cards/老板_猎场主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-06');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-06' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'DAMAGE_BOSS');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_ACTION_POINTS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-06' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'ADD_ACTION_POINTS');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 159, 'B-07', '酒庄主', 3, 'public', 1, 'heal', '恢复一名玩家 3 点血量', '/images/cards/老板_酒庄主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-07');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-07' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'HEAL_PLAYER');

ALTER TABLE `cards` AUTO_INCREMENT = 160;
