-- 部门「你的0来了」诅咒收藏卡。可重复执行。不覆盖已有卡面。
-- 当前已停用：CardCollectionSchemaBootstrap 不再执行本脚本，并把本部门卡 status 设为 0。
-- 下次打开：取消注释 runScript("db/009_zero_dept_cards.sql")，并注释 hideZeroDeptCards()。
INSERT INTO `card_depts` (`id`,`dept_code`,`dept_name`,`dept_category`,`sort_no`,`status`,`created_at`,`updated_at`)
SELECT 5, 'DEPT_ZERO', '你的0来了', 'zero', 5, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `card_depts` WHERE `dept_code` = 'DEPT_ZERO' OR `id` = 5);

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 161, 'Z-01', '夜香倌', 5, 'zero', 0, 'consume', '自己立即失去 2 点血量', '/images/cards/你的0来了_夜香倌.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-01');
UPDATE `cards` SET `description` = '自己立即失去 2 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_夜香倌.webp' WHERE `card_code` = 'Z-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 162, 'Z-02', '痴儿门客', 5, 'zero', 0, 'consume', '抽 1 张牌，本回合霸凌者攻击 +1', '/images/cards/你的0来了_痴儿门客.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-02');
UPDATE `cards` SET `description` = '抽 1 张牌，本回合霸凌者攻击 +1', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_痴儿门客.webp' WHERE `card_code` = 'Z-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'INCREASE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 163, 'Z-03', '花船龟公', 5, 'zero', 0, 'consume', '霸凌者立即恢复 3 点血量', '/images/cards/你的0来了_花船龟公.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-03');
UPDATE `cards` SET `description` = '霸凌者立即恢复 3 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_花船龟公.webp' WHERE `card_code` = 'Z-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'HEAL_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 164, 'Z-04', '粪门巡夜', 5, 'zero', 0, 'consume', '双方各失去 1 点血量，本回合霸凌者攻击 +1', '/images/cards/你的0来了_粪门巡夜.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-04');
UPDATE `cards` SET `description` = '双方各失去 1 点血量，本回合霸凌者攻击 +1', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_粪门巡夜.webp' WHERE `card_code` = 'Z-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'INCREASE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 165, 'Z-05', '溺器承奉', 5, 'zero', 0, 'consume', '自己失去 1 点血量，下回合霸凌者攻击 +2', '/images/cards/你的0来了_溺器承奉.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-05');
UPDATE `cards` SET `description` = '自己失去 1 点血量，下回合霸凌者攻击 +2', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_溺器承奉.webp' WHERE `card_code` = 'Z-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'INCREASE_BOSS_ATTACK', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-05';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 166, 'Z-06', '浴堂奉巾', 5, 'zero', 0, 'consume', '霸凌者恢复 2 点血量，自己失去 1 点血量', '/images/cards/你的0来了_浴堂奉巾.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-06');
UPDATE `cards` SET `description` = '霸凌者恢复 2 点血量，自己失去 1 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_浴堂奉巾.webp' WHERE `card_code` = 'Z-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'HEAL_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-06';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 167, 'Z-07', '亵衣浣手', 5, 'zero', 0, 'consume', '自己立即失去 3 点血量', '/images/cards/你的0来了_亵衣浣手.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-07');
UPDATE `cards` SET `description` = '自己立即失去 3 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_亵衣浣手.webp' WHERE `card_code` = 'Z-07';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-07';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 168, 'Z-08', '双面龟奴', 5, 'zero', 0, 'consume', '本回合霸凌者攻击 +2', '/images/cards/你的0来了_双面龟奴.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-08');
UPDATE `cards` SET `description` = '本回合霸凌者攻击 +2', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_双面龟奴.webp' WHERE `card_code` = 'Z-08';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-08';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'INCREASE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-08';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 169, 'Z-09', '舔靴门客', 5, 'zero', 0, 'consume', '霸凌者立即恢复 4 点血量', '/images/cards/你的0来了_舔靴门客.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-09');
UPDATE `cards` SET `description` = '霸凌者立即恢复 4 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_舔靴门客.webp' WHERE `card_code` = 'Z-09';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-09';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'HEAL_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-09';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 170, 'Z-10', '跪香奴', 5, 'zero', 0, 'consume', '双方各失去 2 点血量', '/images/cards/你的0来了_跪香奴.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-10');
UPDATE `cards` SET `description` = '双方各失去 2 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_跪香奴.webp' WHERE `card_code` = 'Z-10';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-10';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-10';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 171, 'Z-11', '红唇奉盏', 5, 'zero', 0, 'consume', '抽 1 张牌，自己失去 1 点血量', '/images/cards/你的0来了_红唇奉盏.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-11');
UPDATE `cards` SET `description` = '抽 1 张牌，自己失去 1 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_红唇奉盏.webp' WHERE `card_code` = 'Z-11';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-11';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 172, 'Z-12', '鸨母强吻', 5, 'zero', 0, 'consume', '双方各失去 1 点血量，霸凌者恢复 2 点血量', '/images/cards/你的0来了_鸨母强吻.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'Z-12');
UPDATE `cards` SET `description` = '双方各失去 1 点血量，霸凌者恢复 2 点血量', `card_type` = 'consume', `cost` = 0, `dept_id` = 5, `dept_type` = 'zero', `image_url` = '/images/cards/你的0来了_鸨母强吻.webp' WHERE `card_code` = 'Z-12';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'Z-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'HEAL_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'Z-12';

UPDATE `cards` SET `status` = 1 WHERE `dept_type` = 'zero';
UPDATE `card_depts` SET `status` = 1 WHERE `dept_code` = 'DEPT_ZERO';

ALTER TABLE `cards` AUTO_INCREMENT = 173;
