-- 中世纪技术人物收藏卡（T-02～T-05）。可重复执行。不覆盖已有卡面。
-- id 178–181：接在 B-09/B-10、S-25～S-27（173–177）之后。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 178, 'T-02', '察微郎', 3, 'public', 1, 'attack', '立即造成 1 点伤害，并为自己增加 2 点防御', '/images/cards/技术_察微郎.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'T-02');
UPDATE `cards` SET `card_name` = '察微郎', `description` = '立即造成 1 点伤害，并为自己增加 2 点防御', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术_察微郎.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'T-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'T-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 179, 'T-03', '覆面吏', 3, 'public', 2, 'defend', '为自己增加 3 点防御，本回合霸凌者攻击 -1', '/images/cards/技术_覆面吏.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'T-03');
UPDATE `cards` SET `card_name` = '覆面吏', `description` = '为自己增加 3 点防御，本回合霸凌者攻击 -1', `card_type` = 'defend', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术_覆面吏.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'T-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'T-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 180, 'T-04', '浑仪生', 3, 'public', 2, 'draw', '立即造成 2 点伤害，下回合抽 2 张牌', '/images/cards/技术_浑仪生.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'T-04');
UPDATE `cards` SET `card_name` = '浑仪生', `description` = '立即造成 2 点伤害，下回合抽 2 张牌', `card_type` = 'draw', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术_浑仪生.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'T-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'T-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 181, 'T-05', '司历官', 3, 'public', 1, 'heal', '恢复自己 2 点血量，并为一名玩家增加 1 点防御', '/images/cards/技术_司历官.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'T-05');
UPDATE `cards` SET `card_name` = '司历官', `description` = '恢复自己 2 点血量，并为一名玩家增加 1 点防御', `card_type` = 'heal', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术_司历官.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'T-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'T-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-05';

ALTER TABLE `cards` AUTO_INCREMENT = 182;
