-- 中世纪技术人物收藏卡续（T-06～T-07）。可重复执行。不覆盖已有卡面。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 182, 'T-06', '倦籍郎', 3, 'public', 2, 'heal', '恢复自己 2 点血量，下回合再恢复自己 2 点血量', '/images/cards/技术_倦籍郎.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'T-06');
UPDATE `cards` SET `card_name` = '倦籍郎', `description` = '恢复自己 2 点血量，下回合再恢复自己 2 点血量', `card_type` = 'heal', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术_倦籍郎.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'T-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'T-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'HEAL_PLAYER', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-06';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 183, 'T-07', '望楼吏', 3, 'public', 1, 'support', '抽 1 张牌，下回合为自己增加 2 点防御', '/images/cards/技术_望楼吏.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'T-07');
UPDATE `cards` SET `card_name` = '望楼吏', `description` = '抽 1 张牌，下回合为自己增加 2 点防御', `card_type` = 'support', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术_望楼吏.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'T-07';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'T-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'T-07';

ALTER TABLE `cards` AUTO_INCREMENT = 184;
