-- 中世纪老板人物收藏卡（B-11～B-16）。可重复执行。不覆盖已有卡面。
-- id 184–189：接在 T-06/T-07（182–183）之后。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 184, 'B-11', '津梁主', 3, 'public', 2, 'support', '双方各增加 1 点调用机会，并恢复一名玩家 3 点血量', '/images/cards/老板_津梁主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-11');
UPDATE `cards` SET `card_name` = '津梁主', `description` = '双方各增加 1 点调用机会，并恢复一名玩家 3 点血量', `card_type` = 'support', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/老板_津梁主.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'B-11';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'B-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_ACTION_POINTS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-11';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 185, 'B-12', '津埠主', 3, 'public', 2, 'heal', '双方各恢复 1 点血量，下回合再各恢复 2 点血量', '/images/cards/老板_津埠主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-12');
UPDATE `cards` SET `card_name` = '津埠主', `description` = '双方各恢复 1 点血量，下回合再各恢复 2 点血量', `card_type` = 'heal', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/老板_津埠主.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'B-12';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'B-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'HEAL_PLAYER', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-12';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 186, 'B-13', '岭关主', 3, 'public', 3, 'defend', '为自己增加 3 点防御，下回合双方各获得 3 点防御', '/images/cards/老板_岭关主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-13');
UPDATE `cards` SET `card_name` = '岭关主', `description` = '为自己增加 3 点防御，下回合双方各获得 3 点防御', `card_type` = 'defend', `cost` = 3, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/老板_岭关主.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'B-13';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'B-13';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-13';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 3, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-13';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 187, 'B-14', '柜坊主', 3, 'public', 1, 'support', '抽 1 张牌，双方各获得 1 点防御，本回合霸凌者攻击 -1', '/images/cards/老板_柜坊主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-14');
UPDATE `cards` SET `card_name` = '柜坊主', `description` = '抽 1 张牌，双方各获得 1 点防御，本回合霸凌者攻击 -1', `card_type` = 'support', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/老板_柜坊主.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'B-14';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'B-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 3, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-14';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 188, 'B-15', '金帐主', 3, 'public', 3, 'attack', '立即造成 5 点伤害，本回合员工调用机会 +1，并为自己增加 2 点防御', '/images/cards/老板_金帐主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-15');
UPDATE `cards` SET `card_name` = '金帐主', `description` = '立即造成 5 点伤害，本回合员工调用机会 +1，并为自己增加 2 点防御', `card_type` = 'attack', `cost` = 3, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/老板_金帐主.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'B-15';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'B-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 5, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_ACTION_POINTS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 3, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-15';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 189, 'B-16', '宴府主', 3, 'public', 2, 'heal', '双方各恢复 3 点血量', '/images/cards/老板_宴府主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-16');
UPDATE `cards` SET `card_name` = '宴府主', `description` = '双方各恢复 3 点血量', `card_type` = 'heal', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/老板_宴府主.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'B-16';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'B-16';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-16';

ALTER TABLE `cards` AUTO_INCREMENT = 190;
