-- 采购部成员专属防御卡（守护盾兵 / 重甲师立绘）。可重复执行。不覆盖已有卡面。
-- id 211–222：接在 S-43（210）之后。职位为成员英文名。
-- 基础：Kinyond/Harry/Kade/Sandra/Charlene/Amy；收藏：Hermione/Ethan/Carl/Colin/Duane/Kad3。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 211, 'P-26', 'Hermione', 2, 'purchase', 0, 'defend', '为自己增加 3 点防御', '/images/cards/采购_Hermione.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-26');
UPDATE `cards` SET `card_name` = 'Hermione', `description` = '为自己增加 3 点防御', `card_type` = 'defend', `cost` = 0, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Hermione.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'P-26';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-26';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-26';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 212, 'P-27', 'Kinyond', 2, 'purchase', 1, 'defend', '为自己增加 6 点防御', '/images/cards/采购_Kinyond.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-27');
UPDATE `cards` SET `card_name` = 'Kinyond', `description` = '为自己增加 6 点防御', `card_type` = 'defend', `cost` = 1, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Kinyond.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'P-27';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-27';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 6, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-27';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 213, 'P-28', 'Harry', 2, 'purchase', 2, 'defend', '为自己增加 13 点防御', '/images/cards/采购_Harry.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-28');
UPDATE `cards` SET `card_name` = 'Harry', `description` = '为自己增加 13 点防御', `card_type` = 'defend', `cost` = 2, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Harry.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'P-28';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-28';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 13, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-28';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 214, 'P-29', 'Kade', 2, 'purchase', 0, 'defend', '为一名玩家增加 2 点防御', '/images/cards/采购_Kade.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-29');
UPDATE `cards` SET `card_name` = 'Kade', `description` = '为一名玩家增加 2 点防御', `card_type` = 'defend', `cost` = 0, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Kade.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'P-29';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-29';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-29';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 215, 'P-30', 'Sandra', 2, 'purchase', 1, 'defend', '为一名玩家增加 5 点防御', '/images/cards/采购_Sandra.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-30');
UPDATE `cards` SET `card_name` = 'Sandra', `description` = '为一名玩家增加 5 点防御', `card_type` = 'defend', `cost` = 1, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Sandra.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'P-30';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-30';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 5, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-30';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 216, 'P-31', 'Charlene', 2, 'purchase', 2, 'defend', '为一名玩家增加 11 点防御', '/images/cards/采购_Charlene.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-31');
UPDATE `cards` SET `card_name` = 'Charlene', `description` = '为一名玩家增加 11 点防御', `card_type` = 'defend', `cost` = 2, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Charlene.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'P-31';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-31';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 11, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-31';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 217, 'P-32', 'Ethan', 2, 'purchase', 0, 'defend', '为双方各增加 1 点防御', '/images/cards/采购_Ethan.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-32');
UPDATE `cards` SET `card_name` = 'Ethan', `description` = '为双方各增加 1 点防御', `card_type` = 'defend', `cost` = 0, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Ethan.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'P-32';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-32';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-32';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 218, 'P-33', 'Carl', 2, 'purchase', 1, 'defend', '为双方各增加 3 点防御', '/images/cards/采购_Carl.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-33');
UPDATE `cards` SET `card_name` = 'Carl', `description` = '为双方各增加 3 点防御', `card_type` = 'defend', `cost` = 1, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Carl.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'P-33';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-33';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-33';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 219, 'P-34', 'Colin', 2, 'purchase', 2, 'defend', '为双方各增加 7 点防御', '/images/cards/采购_Colin.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-34');
UPDATE `cards` SET `card_name` = 'Colin', `description` = '为双方各增加 7 点防御', `card_type` = 'defend', `cost` = 2, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Colin.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'P-34';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-34';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 7, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-34';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 220, 'P-35', 'Amy', 2, 'purchase', 3, 'defend', '为双方各增加 12 点防御', '/images/cards/采购_Amy.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-35');
UPDATE `cards` SET `card_name` = 'Amy', `description` = '为双方各增加 12 点防御', `card_type` = 'defend', `cost` = 3, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Amy.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'P-35';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-35';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 12, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-35';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 221, 'P-36', 'Duane', 2, 'purchase', 0, 'defend', '队友有盾时先扣盾，挡不住的伤害由你承受', '/images/cards/采购_Duane.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-36');
UPDATE `cards` SET `card_name` = 'Duane', `description` = '队友有盾时先扣盾，挡不住的伤害由你承受', `card_type` = 'defend', `cost` = 0, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Duane.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'P-36';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-36';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'OTHER_PLAYER', 'GUARD_ALLY', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'OTHER_PLAYER', '{"untilConsumed":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-36';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 222, 'P-37', 'Kad3', 2, 'purchase', 1, 'defend', '需自身有盾。自己防御 -1，为队友增加 10 点防御', '/images/cards/采购_Kad3.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-37');
UPDATE `cards` SET `card_name` = 'Kad3', `description` = '需自身有盾。自己防御 -1，为队友增加 10 点防御', `card_type` = 'defend', `cost` = 1, `dept_id` = 2, `dept_type` = 'purchase', `image_url` = '/images/cards/采购_Kad3.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'P-37';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-37';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, -1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-37';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'OTHER_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 10, 'OTHER_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-37';

ALTER TABLE `cards` AUTO_INCREMENT = 223;
