-- 公共部营销大力士成员卡（自残换伤）。可重复执行。不覆盖已有销售/采购同名卡面。
-- id 233–236：接在 LG-04（232）之后。玩法部门为公共部；卡面文件名用「营销_」前缀，图鉴显示营销部。
-- 必须在 018、028、031 之后执行，否则会被 018 停用。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 233, 'MK-01', 'Amber', 3, 'public', 0, 'attack', '自己失去 1 点血量，立即造成 3 点伤害', '/images/cards/营销_Amber.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'MK-01');
UPDATE `cards` SET `card_name` = 'Amber', `description` = '自己失去 1 点血量，立即造成 3 点伤害', `card_type` = 'attack', `cost` = 0, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/营销_Amber.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'MK-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'MK-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 234, 'MK-02', 'Sandra', 3, 'public', 1, 'attack', '自己失去 1 点血量，立即造成 6 点伤害', '/images/cards/营销_Sandra.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'MK-02');
UPDATE `cards` SET `card_name` = 'Sandra', `description` = '自己失去 1 点血量，立即造成 6 点伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/营销_Sandra.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'MK-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'MK-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 6, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 235, 'MK-03', 'Daniel', 3, 'public', 2, 'attack', '自己失去 1 点血量，立即造成 10 点伤害', '/images/cards/营销_Daniel.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'MK-03');
UPDATE `cards` SET `card_name` = 'Daniel', `description` = '自己失去 1 点血量，立即造成 10 点伤害', `card_type` = 'attack', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/营销_Daniel.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'MK-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'MK-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 10, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 236, 'MK-04', 'Kinyond', 3, 'public', 3, 'attack', '自己失去 2 点血量，立即造成 14 点伤害', '/images/cards/营销_Kinyond.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'MK-04');
UPDATE `cards` SET `card_name` = 'Kinyond', `description` = '自己失去 2 点血量，立即造成 14 点伤害', `card_type` = 'attack', `cost` = 3, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/营销_Kinyond.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'MK-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'MK-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 14, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'MK-04';

ALTER TABLE `cards` AUTO_INCREMENT = 237;
