-- 公共部技术部工兵成员卡。可重复执行。不覆盖已有 技术_Ethan / 采购_Kad3 等卡面。
-- id 242–247：接在 DS-05（241）之后。玩法部门为公共部；卡面文件名用「技术部_」前缀，图鉴显示技术部。
-- 必须在 018、028、031、032、035 之后执行，否则会被 018 停用。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 242, 'IT-01', 'Rain', 3, 'public', 1, 'attack', '本回合每当队友对霸凌者造成一段伤害，再额外攻击 2 点', '/images/cards/技术部_Rain.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'IT-01');
UPDATE `cards` SET `card_name` = 'Rain', `description` = '本回合每当队友对霸凌者造成一段伤害，再额外攻击 2 点', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术部_Rain.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'IT-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'IT-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'CHASE_ALLY_ATTACK', 'IMMEDIATE', 0, 99, 'STACK', 0, 2, 'BOSS', '{"expireAtRoundEnd":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 243, 'IT-02', 'Chrissy', 3, 'public', 1, 'attack', '打出后，本回合每当霸凌者实际掉血，再额外失去 1 点生命', '/images/cards/技术部_Chrissy.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'IT-02');
UPDATE `cards` SET `card_name` = 'Chrissy', `description` = '打出后，本回合每当霸凌者实际掉血，再额外失去 1 点生命', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术部_Chrissy.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'IT-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'IT-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'ON_BOSS_HP_LOSS', 'IMMEDIATE', 0, 99, 'STACK', 0, 1, 'BOSS', '{"expireAtRoundEnd":true,"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 244, 'IT-03', 'Ethan', 3, 'public', 1, 'attack', '下一次自己被霸凌者打中后，对霸凌者造成 15 点伤害', '/images/cards/技术部_Ethan.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'IT-03');
UPDATE `cards` SET `card_name` = 'Ethan', `description` = '下一次自己被霸凌者打中后，对霸凌者造成 15 点伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术部_Ethan.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'IT-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'IT-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'COUNTER_ON_HIT', 'IMMEDIATE', 0, 1, 'STACK', 0, 15, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 245, 'IT-04', 'Iris', 3, 'public', 1, 'skill', '躲避接下来第 1 次受到的霸凌者攻击（该次伤害为 0）', '/images/cards/技术部_Iris.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'IT-04');
UPDATE `cards` SET `card_name` = 'Iris', `description` = '躲避接下来第 1 次受到的霸凌者攻击（该次伤害为 0）', `card_type` = 'skill', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术部_Iris.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'IT-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'IT-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DODGE_NEXT_HIT', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 246, 'IT-05', 'Dylan', 3, 'public', 1, 'attack', '将自己当前防御清 0，对霸凌者造成等额伤害', '/images/cards/技术部_Dylan.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'IT-05');
UPDATE `cards` SET `card_name` = 'Dylan', `description` = '将自己当前防御清 0，对霸凌者造成等额伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术部_Dylan.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'IT-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'IT-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'CONVERT_SHIELD_TO_DAMAGE', 'IMMEDIATE', 0, 1, 'STACK', 0, 0, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-05';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 247, 'IT-06', 'Kad3', 3, 'public', 1, 'attack', '双方玩家与霸凌者各失去 9 点生命', '/images/cards/技术部_Kad3.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'IT-06');
UPDATE `cards` SET `card_name` = 'Kad3', `description` = '双方玩家与霸凌者各失去 9 点生命', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/技术部_Kad3.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'IT-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'IT-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 9, 'ALL_PLAYERS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 9, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'IT-06';

ALTER TABLE `cards` AUTO_INCREMENT = 248;
