-- 老板中世纪收藏卡。可重复执行。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 151, 'B-01', '领主', 3, 'public', 3, 'attack', '立即造成 4 点伤害，并为一名玩家增加 2 点防御', '/images/cards/老板_领主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-01');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-01' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'DAMAGE_BOSS');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-01' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'ADD_SHIELD');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 152, 'B-02', '城主', 3, 'public', 2, 'defend', '双方各获得 2 点防御', '/images/cards/老板_城主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-02');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-02' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'ADD_SHIELD');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 153, 'B-03', '庄主', 3, 'public', 1, 'support', '立即造成 2 点伤害，并抽 1 张牌', '/images/cards/老板_庄主.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'B-03');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-03' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 1 AND e.effect_type = 'DAMAGE_BOSS');
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'B-03' AND NOT EXISTS (SELECT 1 FROM `card_effects` e WHERE e.card_id = c.id AND e.effect_order = 2 AND e.effect_type = 'DRAW_CARDS');

ALTER TABLE `cards` AUTO_INCREMENT = 154;
