-- 公共部雇佣兵基础卡（1 费）。可重复执行。不覆盖已有卡面。
-- id 223–228：接在 P-37（222）之后。玩法部门为公共部；卡面文件名用「雇佣兵_」前缀。
-- 必须在 018 之后执行，否则会被 018 停用。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 223, 'M-01', '客服剑士', 3, 'public', 1, 'attack', '立即造成 3 点伤害', '/images/cards/雇佣兵_客服剑士.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'M-01');
UPDATE `cards` SET `card_name` = '客服剑士', `description` = '立即造成 3 点伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/雇佣兵_客服剑士.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'M-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'M-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 224, 'M-02', '装备重甲师', 3, 'public', 1, 'defend', '为自己增加 4 点防御', '/images/cards/雇佣兵_装备重甲师.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'M-02');
UPDATE `cards` SET `card_name` = '装备重甲师', `description` = '为自己增加 4 点防御', `card_type` = 'defend', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/雇佣兵_装备重甲师.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'M-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'M-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 225, 'M-03', '文艺射手', 3, 'public', 1, 'attack', '立即对敌人造成 1 点穿透伤害（无视护盾）', '/images/cards/雇佣兵_文艺射手.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'M-03');
UPDATE `cards` SET `card_name` = '文艺射手', `description` = '立即对敌人造成 1 点穿透伤害（无视护盾）', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/雇佣兵_文艺射手.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'M-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'M-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 226, 'M-04', '街艺大力士', 3, 'public', 1, 'attack', '自己失去 1 点血量，立即造成 5 点伤害', '/images/cards/雇佣兵_街艺大力士.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'M-04');
UPDATE `cards` SET `card_name` = '街艺大力士', `description` = '自己失去 1 点血量，立即造成 5 点伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/雇佣兵_街艺大力士.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'M-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'M-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DAMAGE_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 5, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 227, 'M-05', '物流骑士', 3, 'public', 1, 'attack', '立即造成 2 点伤害，再造成 2 点伤害', '/images/cards/雇佣兵_物流骑士.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'M-05');
UPDATE `cards` SET `card_name` = '物流骑士', `description` = '立即造成 2 点伤害，再造成 2 点伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/雇佣兵_物流骑士.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'M-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'M-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-05';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 228, 'M-06', '补给牧师', 3, 'public', 1, 'heal', '恢复一名玩家 2 点血量', '/images/cards/雇佣兵_补给牧师.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'M-06');
UPDATE `cards` SET `card_name` = '补给牧师', `description` = '恢复一名玩家 2 点血量', `card_type` = 'heal', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/雇佣兵_补给牧师.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'M-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'M-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'M-06';

ALTER TABLE `cards` AUTO_INCREMENT = 229;
