-- 公共部财务部补给牧师成员卡。可重复执行。不覆盖已有 物流_Riley / 采购_Charlene / 物流_Felicity / 采购_Hermione / 采购_Colin / 设计部_Nico 等卡面。
-- id 248–253：接在 IT-06（247）之后。玩法部门为公共部；卡面文件名用「财务部_」前缀，图鉴显示财务部。
-- 必须在 018、028、031、032、035、036 之后执行，否则会被 018 停用。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 248, 'FN-01', 'Riley', 3, 'public', 0, 'heal', '恢复一名玩家 2 点血量', '/images/cards/财务部_Riley.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'FN-01');
UPDATE `cards` SET `card_name` = 'Riley', `description` = '恢复一名玩家 2 点血量', `card_type` = 'heal', `cost` = 0, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/财务部_Riley.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'FN-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'FN-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 249, 'FN-02', 'Charlene', 3, 'public', 1, 'heal', '恢复一名玩家 3 点血量', '/images/cards/财务部_Charlene.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'FN-02');
UPDATE `cards` SET `card_name` = 'Charlene', `description` = '恢复一名玩家 3 点血量', `card_type` = 'heal', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/财务部_Charlene.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'FN-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'FN-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 250, 'FN-03', 'Felicity', 3, 'public', 2, 'heal', '恢复一名玩家 5 点血量', '/images/cards/财务部_Felicity.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'FN-03');
UPDATE `cards` SET `card_name` = 'Felicity', `description` = '恢复一名玩家 5 点血量', `card_type` = 'heal', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/财务部_Felicity.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'FN-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'FN-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 5, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 251, 'FN-04', 'Hermione', 3, 'public', 3, 'heal', '恢复一名玩家 20 点血量，并为霸凌者恢复 20 点血量', '/images/cards/财务部_Hermione.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'FN-04');
UPDATE `cards` SET `card_name` = 'Hermione', `description` = '恢复一名玩家 20 点血量，并为霸凌者恢复 20 点血量', `card_type` = 'heal', `cost` = 3, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/财务部_Hermione.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'FN-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'FN-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 20, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'HEAL_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 20, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 252, 'FN-05', 'Colin', 3, 'public', 1, 'skill', '本回合员工调用机会 +1', '/images/cards/财务部_Colin.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'FN-05');
UPDATE `cards` SET `card_name` = 'Colin', `description` = '本回合员工调用机会 +1', `card_type` = 'skill', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/财务部_Colin.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'FN-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'FN-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_ACTION_POINTS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-05';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 253, 'FN-06', 'Nico', 3, 'public', 1, 'heal', '恢复一名玩家 1 点血量，持续 3 回合（含本回合）', '/images/cards/财务部_Nico.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'FN-06');
UPDATE `cards` SET `card_name` = 'Nico', `description` = '恢复一名玩家 1 点血量，持续 3 回合（含本回合）', `card_type` = 'heal', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/财务部_Nico.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'FN-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'FN-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'ROUND_START', 1, 2, 'STACK', 2, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'FN-06';

ALTER TABLE `cards` AUTO_INCREMENT = 254;
