-- 公共部人事部占卜家成员卡。可重复执行。不覆盖已有 销售_Ancy / 采购_Kade / 采购_Duane / 技术部_Ethan / 采购_Amy / 采购_Harry / 物流_Carl 等卡面。
-- id 254–260：接在 FN-06（253）之后。玩法部门为公共部；卡面文件名用「人事部_」前缀，图鉴显示人事部。
-- 必须在 018、028、031、032、035、036、037 之后执行，否则会被 018 停用。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 254, 'HR-01', 'Ancy', 3, 'public', 1, 'buff', '下一张造成伤害的牌，伤害 ×2（可跨回合；连击每段都 ×2）', '/images/cards/人事部_Ancy.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-01');
UPDATE `cards` SET `card_name` = 'Ancy', `description` = '下一张造成伤害的牌，伤害 ×2（可跨回合；连击每段都 ×2）', `card_type` = 'buff', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Ancy.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'MULTIPLY_NEXT_CARD', 'NEXT_CARD', 0, 1, 'REPLACE', 0, 2, 'SELF', '{"multiplyEffectTypes":["DAMAGE_BOSS"],"consumeAfterUse":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 255, 'HR-02', 'Kade', 3, 'public', 1, 'buff', '下一次获得的防御 ×2', '/images/cards/人事部_Kade.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-02');
UPDATE `cards` SET `card_name` = 'Kade', `description` = '下一次获得的防御 ×2', `card_type` = 'buff', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Kade.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'MULTIPLY_NEXT_CARD', 'NEXT_CARD', 0, 1, 'REPLACE', 0, 2, 'SELF', '{"multiplyEffectTypes":["ADD_SHIELD"],"consumeAfterUse":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 256, 'HR-03', 'Duane', 3, 'public', 1, 'buff', '将自己当前防御值 ×2', '/images/cards/人事部_Duane.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-03');
UPDATE `cards` SET `card_name` = 'Duane', `description` = '将自己当前防御值 ×2', `card_type` = 'buff', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Duane.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'MULTIPLY_CURRENT_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 257, 'HR-04', 'Ethan', 3, 'public', 1, 'buff', '本回合所有攻击伤害 +2（连击每段都 +2）', '/images/cards/人事部_Ethan.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-04');
UPDATE `cards` SET `card_name` = 'Ethan', `description` = '本回合所有攻击伤害 +2（连击每段都 +2）', `card_type` = 'buff', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Ethan.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_TURN_DAMAGE', 'IMMEDIATE', 0, 99, 'STACK', 0, 2, 'SELF', '{"expireAtRoundEnd":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 258, 'HR-05', 'Amy', 3, 'public', 2, 'buff', '本回合所有攻击伤害 ×2（连击每段都翻倍）', '/images/cards/人事部_Amy.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-05');
UPDATE `cards` SET `card_name` = 'Amy', `description` = '本回合所有攻击伤害 ×2（连击每段都翻倍）', `card_type` = 'buff', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Amy.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'MULTIPLY_TURN_DAMAGE', 'IMMEDIATE', 0, 99, 'STACK', 0, 2, 'SELF', '{"expireAtRoundEnd":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-05';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 259, 'HR-06', 'Harry', 3, 'public', 2, 'buff', '本回合获得的防御 ×2', '/images/cards/人事部_Harry.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-06');
UPDATE `cards` SET `card_name` = 'Harry', `description` = '本回合获得的防御 ×2', `card_type` = 'buff', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Harry.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'MULTIPLY_TURN_SHIELD', 'IMMEDIATE', 0, 99, 'STACK', 0, 2, 'SELF', '{"expireAtRoundEnd":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-06';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 260, 'HR-07', 'Carl', 3, 'public', 1, 'buff', '查看下回合抽到的卡牌', '/images/cards/人事部_Carl.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'HR-07');
UPDATE `cards` SET `card_name` = 'Carl', `description` = '查看下回合抽到的卡牌', `card_type` = 'buff', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/人事部_Carl.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'HR-07';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'HR-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'PEEK_NEXT_DRAW', 'IMMEDIATE', 0, 1, 'REPLACE', 0, 5, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'HR-07';

ALTER TABLE `cards` AUTO_INCREMENT = 261;
