-- 收藏卡：需胜利解锁；含效果配置。可重复执行。
SET @exist := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cards' AND COLUMN_NAME = 'require_unlock');
SET @sql := IF(@exist = 0, 'ALTER TABLE `cards` ADD COLUMN `require_unlock` tinyint NOT NULL DEFAULT 0 COMMENT ''1需胜利解锁才可进入对局'' AFTER `is_unique`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE `cards` SET `require_unlock` = 1 WHERE `card_code` IN ('O-16','O-17','O-18','O-19');

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 90, 'S-07', '摊贩', 1, 'sales', 0, 'attack', '立即造成 1 点伤害，并为一名玩家增加 1 点防御', '/images/cards/销售_摊贩.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-07');
UPDATE `cards` SET `description` = '立即造成 1 点伤害，并为一名玩家增加 1 点防御', `card_type` = 'attack', `cost` = 0 WHERE `card_code` = 'S-07';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-07';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 91, 'S-08', '货郎', 1, 'sales', 0, 'draw', '抽 1 张牌', '/images/cards/销售_货郎.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-08');
UPDATE `cards` SET `description` = '抽 1 张牌', `card_type` = 'draw', `cost` = 0 WHERE `card_code` = 'S-08';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-08';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-08';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 92, 'S-09', '卖艺货郎', 1, 'sales', 0, 'attack', '立即造成 1 点伤害，并抽 1 张牌', '/images/cards/销售_卖艺货郎.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-09');
UPDATE `cards` SET `description` = '立即造成 1 点伤害，并抽 1 张牌', `card_type` = 'attack', `cost` = 0 WHERE `card_code` = 'S-09';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-09';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-09';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-09';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 93, 'S-10', '酒娘', 1, 'sales', 1, 'attack', '立即造成 2 点伤害，并恢复自己 1 点血量', '/images/cards/销售_酒娘.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-10');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，并恢复自己 1 点血量', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'S-10';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-10';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-10';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-10';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 94, 'S-11', '面包师', 1, 'sales', 1, 'attack', '本回合造成 1 点伤害，下回合再造成 2 点', '/images/cards/销售_面包师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-11');
UPDATE `cards` SET `description` = '本回合造成 1 点伤害，下回合再造成 2 点', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'S-11';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-11';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 95, 'S-12', '珠串商', 1, 'sales', 1, 'attack', '立即造成 2 点伤害，并为一名玩家增加 1 点防御', '/images/cards/销售_珠串商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-12');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，并为一名玩家增加 1 点防御', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'S-12';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-12';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 96, 'S-13', '香囊商', 1, 'sales', 1, 'attack', '立即造成 2 点伤害，并恢复一名玩家 1 点血量', '/images/cards/销售_香囊商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-13');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，并恢复一名玩家 1 点血量', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'S-13';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-13';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-13';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-13';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 97, 'S-14', '绒帽商', 1, 'sales', 1, 'support', '立即造成 1 点伤害，本回合霸凌者攻击 -1', '/images/cards/销售_绒帽商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-14');
UPDATE `cards` SET `description` = '立即造成 1 点伤害，本回合霸凌者攻击 -1', `card_type` = 'support', `cost` = 1 WHERE `card_code` = 'S-14';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-14';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 98, 'S-15', '酒商', 1, 'sales', 2, 'attack', '立即造成 3 点伤害，并抽 1 张牌', '/images/cards/销售_酒商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-15');
UPDATE `cards` SET `description` = '立即造成 3 点伤害，并抽 1 张牌', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'S-15';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-15';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 99, 'S-16', '衡器商', 1, 'sales', 2, 'support', '立即造成 2 点伤害，本回合霸凌者攻击 -2', '/images/cards/销售_衡器商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-16');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，本回合霸凌者攻击 -2', `card_type` = 'support', `cost` = 2 WHERE `card_code` = 'S-16';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-16';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-16';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-16';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 100, 'S-17', '布商', 1, 'sales', 2, 'attack', '本回合造成 2 点伤害，下回合再造成 3 点', '/images/cards/销售_布商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-17');
UPDATE `cards` SET `description` = '本回合造成 2 点伤害，下回合再造成 3 点', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'S-17';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-17';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-17';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-17';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 101, 'S-18', '行商', 1, 'sales', 2, 'attack', '立即造成 2 点伤害，并抽 1 张牌', '/images/cards/销售_行商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-18');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，并抽 1 张牌', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'S-18';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-18';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-18';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-18';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 102, 'S-19', '杂货商', 1, 'sales', 2, 'attack', '立即造成 2 点伤害，双方各获得 1 点防御', '/images/cards/销售_杂货商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-19');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，双方各获得 1 点防御', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'S-19';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-19';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-19';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-19';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 103, 'S-20', '花边商', 1, 'sales', 2, 'attack', '立即造成 3 点伤害，下回合再造成 1 点', '/images/cards/销售_花边商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-20');
UPDATE `cards` SET `description` = '立即造成 3 点伤害，下回合再造成 1 点', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'S-20';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-20';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-20';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-20';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 104, 'S-21', '公会会长', 1, 'sales', 3, 'attack', '立即造成 4 点伤害，双方各获得 1 点防御', '/images/cards/销售_公会会长.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-21');
UPDATE `cards` SET `description` = '立即造成 4 点伤害，双方各获得 1 点防御', `card_type` = 'attack', `cost` = 3 WHERE `card_code` = 'S-21';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-21';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-21';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-21';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 105, 'S-22', '香料商', 1, 'sales', 3, 'attack', '本回合造成 3 点伤害，下回合再造成 3 点', '/images/cards/销售_香料商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-22');
UPDATE `cards` SET `description` = '本回合造成 3 点伤害，下回合再造成 3 点', `card_type` = 'attack', `cost` = 3 WHERE `card_code` = 'S-22';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-22';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-22';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-22';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 106, 'S-23', '旅店掌柜', 1, 'sales', 3, 'attack', '立即造成 2 点伤害，双方各获得 2 点防御', '/images/cards/销售_旅店掌柜.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-23');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，双方各获得 2 点防御', `card_type` = 'attack', `cost` = 3 WHERE `card_code` = 'S-23';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-23';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-23';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-23';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 107, 'S-24', '绸缎商', 1, 'sales', 3, 'attack', '立即造成 4 点伤害，并抽 1 张牌', '/images/cards/销售_绸缎商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-24');
UPDATE `cards` SET `description` = '立即造成 4 点伤害，并抽 1 张牌', `card_type` = 'attack', `cost` = 3 WHERE `card_code` = 'S-24';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-24';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-24';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-24';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 108, 'P-05', '掮客', 2, 'purchase', 0, 'defend', '为自己增加 2 点防御', '/images/cards/采购_掮客.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-05');
UPDATE `cards` SET `description` = '为自己增加 2 点防御', `card_type` = 'defend', `cost` = 0 WHERE `card_code` = 'P-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-05';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 109, 'P-06', '采办官', 2, 'purchase', 0, 'defend', '本回合增加 1 点防御，下回合再增加 1 点', '/images/cards/采购_采办官.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-06');
UPDATE `cards` SET `description` = '本回合增加 1 点防御，下回合再增加 1 点', `card_type` = 'defend', `cost` = 0 WHERE `card_code` = 'P-06';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-06';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-06';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 110, 'P-07', '仓储管事', 2, 'purchase', 1, 'defend', '本回合增加 2 点防御，下回合再增加 1 点', '/images/cards/采购_仓储管事.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-07');
UPDATE `cards` SET `description` = '本回合增加 2 点防御，下回合再增加 1 点', `card_type` = 'defend', `cost` = 1 WHERE `card_code` = 'P-07';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-07';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-07';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 111, 'P-08', '园圃办货', 2, 'purchase', 1, 'defend', '为一名玩家增加 2 点防御，并恢复 1 点血量', '/images/cards/采购_园圃办货.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-08');
UPDATE `cards` SET `description` = '为一名玩家增加 2 点防御，并恢复 1 点血量', `card_type` = 'defend', `cost` = 1 WHERE `card_code` = 'P-08';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-08';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-08';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-08';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 112, 'P-09', '丝线采买', 2, 'purchase', 1, 'draw', '抽 1 张牌，并为一名玩家增加 1 点防御', '/images/cards/采购_丝线采买.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-09');
UPDATE `cards` SET `description` = '抽 1 张牌，并为一名玩家增加 1 点防御', `card_type` = 'draw', `cost` = 1 WHERE `card_code` = 'P-09';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-09';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-09';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-09';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 113, 'P-10', '账册核验', 2, 'purchase', 1, 'support', '为一名玩家增加 2 点防御，本回合霸凌者攻击 -1', '/images/cards/采购_账册核验.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-10');
UPDATE `cards` SET `description` = '为一名玩家增加 2 点防御，本回合霸凌者攻击 -1', `card_type` = 'support', `cost` = 1 WHERE `card_code` = 'P-10';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-10';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-10';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'REDUCE_BOSS_ATTACK', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-10';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 114, 'P-11', '粮秣官', 2, 'purchase', 2, 'defend', '为一名玩家增加 2 点防御，并恢复 2 点血量', '/images/cards/采购_粮秣官.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-11');
UPDATE `cards` SET `description` = '为一名玩家增加 2 点防御，并恢复 2 点血量', `card_type` = 'defend', `cost` = 2 WHERE `card_code` = 'P-11';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-11';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-11';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 115, 'P-12', '暗市办货', 2, 'purchase', 2, 'defend', '为自己增加 4 点防御', '/images/cards/采购_暗市办货.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-12');
UPDATE `cards` SET `description` = '为自己增加 4 点防御', `card_type` = 'defend', `cost` = 2 WHERE `card_code` = 'P-12';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-12';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-12';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 116, 'P-13', '书坊采买', 2, 'purchase', 2, 'defend', '本回合增加 3 点防御，下回合再增加 1 点', '/images/cards/采购_书坊采买.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-13');
UPDATE `cards` SET `description` = '本回合增加 3 点防御，下回合再增加 1 点', `card_type` = 'defend', `cost` = 2 WHERE `card_code` = 'P-13';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-13';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-13';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-13';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 117, 'P-14', '学府采办', 2, 'purchase', 2, 'draw', '为一名玩家增加 2 点防御，并抽 1 张牌', '/images/cards/采购_学府采办.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-14');
UPDATE `cards` SET `description` = '为一名玩家增加 2 点防御，并抽 1 张牌', `card_type` = 'draw', `cost` = 2 WHERE `card_code` = 'P-14';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-14';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-14';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 118, 'P-15', '珍宝估价', 2, 'purchase', 2, 'defend', '为一名玩家增加 3 点防御，并对霸凌者造成 1 点伤害', '/images/cards/采购_珍宝估价.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-15');
UPDATE `cards` SET `description` = '为一名玩家增加 3 点防御，并对霸凌者造成 1 点伤害', `card_type` = 'defend', `cost` = 2 WHERE `card_code` = 'P-15';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-15';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-15';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 119, 'P-16', '军需官', 2, 'purchase', 3, 'defend', '双方各获得 3 点防御', '/images/cards/采购_军需官.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-16');
UPDATE `cards` SET `description` = '双方各获得 3 点防御', `card_type` = 'defend', `cost` = 3 WHERE `card_code` = 'P-16';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-16';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-16';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 120, 'P-17', '王室采办', 2, 'purchase', 3, 'defend', '本回合增加 4 点防御，下回合再增加 2 点', '/images/cards/采购_王室采办.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-17');
UPDATE `cards` SET `description` = '本回合增加 4 点防御，下回合再增加 2 点', `card_type` = 'defend', `cost` = 3 WHERE `card_code` = 'P-17';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-17';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-17';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-17';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 121, 'P-18', '贡银采办', 2, 'purchase', 3, 'defend', '双方各获得 2 点防御，并抽 1 张牌', '/images/cards/采购_贡银采办.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'P-18');
UPDATE `cards` SET `description` = '双方各获得 2 点防御，并抽 1 张牌', `card_type` = 'defend', `cost` = 3 WHERE `card_code` = 'P-18';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'P-18';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-18';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'P-18';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 122, 'O-20', '绣娘', 3, 'public', 1, 'attack', '立即造成 2 点伤害，下回合为一名玩家增加 1 点防御', '/images/cards/设计_绣娘.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-20');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，下回合为一名玩家增加 1 点防御', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'O-20';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-20';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-20';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-20';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 123, 'O-21', '纹章师', 3, 'public', 1, 'defend', '为一名玩家增加 2 点防御，并对霸凌者造成 1 点伤害', '/images/cards/设计_纹章师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-21');
UPDATE `cards` SET `description` = '为一名玩家增加 2 点防御，并对霸凌者造成 1 点伤害', `card_type` = 'defend', `cost` = 1 WHERE `card_code` = 'O-21';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-21';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-21';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-21';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 124, 'O-22', '泥金师', 3, 'public', 2, 'attack', '立即造成 3 点伤害，并恢复一名玩家 1 点血量', '/images/cards/设计_泥金师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-22');
UPDATE `cards` SET `description` = '立即造成 3 点伤害，并恢复一名玩家 1 点血量', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'O-22';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-22';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-22';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-22';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 125, 'O-23', '营造师', 3, 'public', 2, 'defend', '本回合增加 1 点防御，下回合再增加 3 点', '/images/cards/设计_营造师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-23');
UPDATE `cards` SET `description` = '本回合增加 1 点防御，下回合再增加 3 点', `card_type` = 'defend', `cost` = 2 WHERE `card_code` = 'O-23';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-23';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-23';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-23';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 126, 'O-24', '舆图师', 3, 'public', 2, 'draw', '抽 1 张牌，下回合再抽 1 张', '/images/cards/设计_舆图师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-24');
UPDATE `cards` SET `description` = '抽 1 张牌，下回合再抽 1 张', `card_type` = 'draw', `cost` = 2 WHERE `card_code` = 'O-24';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-24';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-24';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-24';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 127, 'O-25', '果贩', 3, 'public', 0, 'attack', '立即造成 1 点伤害，并恢复一名玩家 1 点血量', '/images/cards/市场_果贩.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-25');
UPDATE `cards` SET `description` = '立即造成 1 点伤害，并恢复一名玩家 1 点血量', `card_type` = 'attack', `cost` = 0 WHERE `card_code` = 'O-25';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-25';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-25';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-25';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 128, 'O-26', '宫廷抄写员', 3, 'public', 0, 'attack', '立即造成 1 点伤害，下回合抽 1 张牌', '/images/cards/文员_宫廷抄写员.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-26');
UPDATE `cards` SET `description` = '立即造成 1 点伤害，下回合抽 1 张牌', `card_type` = 'attack', `cost` = 0 WHERE `card_code` = 'O-26';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-26';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-26';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-26';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 129, 'O-27', '守门人', 3, 'public', 0, 'defend', '双方各获得 1 点防御', '/images/cards/安保_守门人.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-27');
UPDATE `cards` SET `description` = '双方各获得 1 点防御', `card_type` = 'defend', `cost` = 0 WHERE `card_code` = 'O-27';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-27';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-27';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 130, 'O-28', '学徒', 3, 'public', 0, 'draw', '下回合抽 1 张牌', '/images/cards/行政_学徒.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-28');
UPDATE `cards` SET `description` = '下回合抽 1 张牌', `card_type` = 'draw', `cost` = 0 WHERE `card_code` = 'O-28';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-28';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-28';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 131, 'O-29', '花使', 3, 'public', 1, 'attack', '立即造成 1 点伤害，双方各恢复 1 点血量', '/images/cards/礼仪_花使.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-29');
UPDATE `cards` SET `description` = '立即造成 1 点伤害，双方各恢复 1 点血量', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'O-29';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-29';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-29';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-29';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 132, 'O-30', '草药师', 3, 'public', 1, 'heal', '恢复一名玩家 2 点血量，并为一名玩家增加 1 点防御', '/images/cards/医疗_草药师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-30');
UPDATE `cards` SET `description` = '恢复一名玩家 2 点血量，并为一名玩家增加 1 点防御', `card_type` = 'heal', `cost` = 1 WHERE `card_code` = 'O-30';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-30';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-30';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-30';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 133, 'O-31', '司膳', 3, 'public', 1, 'heal', '本回合恢复 1 点，下回合再恢复 2 点', '/images/cards/餐饮_司膳.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-31');
UPDATE `cards` SET `description` = '本回合恢复 1 点，下回合再恢复 2 点', `card_type` = 'heal', `cost` = 1 WHERE `card_code` = 'O-31';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-31';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-31';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-31';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 134, 'O-32', '牧羊女', 3, 'public', 1, 'defend', '双方各获得 1 点防御，并恢复一名玩家 1 点血量', '/images/cards/农业_牧羊女.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-32');
UPDATE `cards` SET `description` = '双方各获得 1 点防御，并恢复一名玩家 1 点血量', `card_type` = 'defend', `cost` = 1 WHERE `card_code` = 'O-32';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-32';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-32';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-32';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 135, 'O-33', '捕鼠师', 3, 'public', 1, 'attack', '立即造成 2 点伤害，并为自己增加 1 点防御', '/images/cards/仓储_捕鼠师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-33');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，并为自己增加 1 点防御', `card_type` = 'attack', `cost` = 1 WHERE `card_code` = 'O-33';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-33';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-33';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-33';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 136, 'O-34', '藏书吏', 3, 'public', 1, 'draw', '抽 1 张牌，下回合对霸凌者造成 1 点伤害', '/images/cards/行政_藏书吏.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-34');
UPDATE `cards` SET `description` = '抽 1 张牌，下回合对霸凌者造成 1 点伤害', `card_type` = 'draw', `cost` = 1 WHERE `card_code` = 'O-34';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-34';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-34';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-34';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 137, 'O-35', '弓箭手', 3, 'public', 2, 'attack', '本回合造成 1 点伤害，下回合再造成 4 点', '/images/cards/军事_弓箭手.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-35');
UPDATE `cards` SET `description` = '本回合造成 1 点伤害，下回合再造成 4 点', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'O-35';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-35';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-35';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-35';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 138, 'O-36', '厨子', 3, 'public', 2, 'heal', '恢复一名玩家 3 点血量，并抽 1 张牌', '/images/cards/餐饮_厨子.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-36');
UPDATE `cards` SET `description` = '恢复一名玩家 3 点血量，并抽 1 张牌', `card_type` = 'heal', `cost` = 2 WHERE `card_code` = 'O-36';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-36';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-36';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-36';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 139, 'O-37', '渔妇', 3, 'public', 2, 'heal', '本回合恢复 2 点，下回合再恢复 2 点', '/images/cards/渔业_渔妇.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-37');
UPDATE `cards` SET `description` = '本回合恢复 2 点，下回合再恢复 2 点', `card_type` = 'heal', `cost` = 2 WHERE `card_code` = 'O-37';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-37';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-37';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'HEAL_PLAYER', 'ROUND_START', 1, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-37';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 140, 'O-38', '织工', 3, 'public', 2, 'defend', '双方各获得 1 点防御，下回合再各获得 1 点', '/images/cards/生产_织工.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-38');
UPDATE `cards` SET `description` = '双方各获得 1 点防御，下回合再各获得 1 点', `card_type` = 'defend', `cost` = 2 WHERE `card_code` = 'O-38';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-38';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ALL_PLAYERS', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-38';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ALL_PLAYERS', 'ADD_SHIELD', 'ROUND_START', 1, 1, 'STACK', 0, 1, 'ALL_PLAYERS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-38';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 141, 'O-39', '染匠', 3, 'public', 2, 'attack', '下回合造成 4 点伤害', '/images/cards/生产_染匠.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-39');
UPDATE `cards` SET `description` = '下回合造成 4 点伤害', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'O-39';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-39';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-39';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 142, 'O-40', '机械工匠', 3, 'public', 2, 'attack', '立即造成 2 点伤害，并为一名玩家增加 2 点防御', '/images/cards/技术_机械工匠.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-40');
UPDATE `cards` SET `description` = '立即造成 2 点伤害，并为一名玩家增加 2 点防御', `card_type` = 'attack', `cost` = 2 WHERE `card_code` = 'O-40';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-40';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-40';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'ANY_PLAYER', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-40';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 143, 'O-41', '学者', 3, 'public', 2, 'heal', '恢复一名玩家 2 点血量，并抽 1 张牌', '/images/cards/教育_学者.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-41');
UPDATE `cards` SET `description` = '恢复一名玩家 2 点血量，并抽 1 张牌', `card_type` = 'heal', `cost` = 2 WHERE `card_code` = 'O-41';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-41';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'ANY_PLAYER', 'HEAL_PLAYER', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'ANY_PLAYER', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-41';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'DRAW_CARDS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-41';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 144, 'O-42', '珠宝商', 3, 'public', 3, 'attack', '立即造成 5 点伤害，并为自己增加 1 点防御', '/images/cards/零售_珠宝商.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-42');
UPDATE `cards` SET `description` = '立即造成 5 点伤害，并为自己增加 1 点防御', `card_type` = 'attack', `cost` = 3 WHERE `card_code` = 'O-42';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-42';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 5, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-42';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-42';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 145, 'O-43', '骑士', 3, 'public', 3, 'defend', '立即造成 3 点伤害，并为自己增加 3 点防御', '/images/cards/安保_骑士.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-43');
UPDATE `cards` SET `description` = '立即造成 3 点伤害，并为自己增加 3 点防御', `card_type` = 'defend', `cost` = 3 WHERE `card_code` = 'O-43';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-43';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-43';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-43';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 146, 'O-44', '占卜师', 3, 'public', 3, 'support', '本回合员工调用机会 +1，并使自己打出的下一张牌数值效果翻倍', '/images/cards/玄学_占卜师.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'O-44');
UPDATE `cards` SET `description` = '本回合员工调用机会 +1，并使自己打出的下一张牌数值效果翻倍', `card_type` = 'support', `cost` = 3 WHERE `card_code` = 'O-44';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'O-44';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'SELF', 'ADD_ACTION_POINTS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-44';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'MULTIPLY_NEXT_CARD', 'NEXT_CARD', 0, 1, 'REPLACE', 0, 2, 'SELF', '{"consumeAfterUse": true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'O-44';

ALTER TABLE `cards` AUTO_INCREMENT = 147;
