-- 销售部成员专属攻击卡（客服剑士立绘）。可重复执行。不覆盖已有卡面。
-- id 202–210：接在 P-25（201）之后。职位为成员英文名。
-- 基础：Colin/Carl/Nico/Felicity/Riley/Daniel；收藏：Amy/Kinyond/Kade。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 202, 'S-35', 'Colin', 1, 'sales', 0, 'attack', '立即造成 2 点伤害', '/images/cards/销售_Colin.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-35');
UPDATE `cards` SET `card_name` = 'Colin', `description` = '立即造成 2 点伤害', `card_type` = 'attack', `cost` = 0, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Colin.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'S-35';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-35';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-35';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 203, 'S-36', 'Carl', 1, 'sales', 1, 'attack', '立即造成 4 点伤害', '/images/cards/销售_Carl.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-36');
UPDATE `cards` SET `card_name` = 'Carl', `description` = '立即造成 4 点伤害', `card_type` = 'attack', `cost` = 1, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Carl.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'S-36';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-36';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-36';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 204, 'S-37', 'Nico', 1, 'sales', 2, 'attack', '立即造成 9 点伤害', '/images/cards/销售_Nico.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-37');
UPDATE `cards` SET `card_name` = 'Nico', `description` = '立即造成 9 点伤害', `card_type` = 'attack', `cost` = 2, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Nico.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'S-37';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-37';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 9, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-37';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 205, 'S-38', 'Amy', 1, 'sales', 3, 'attack', '立即造成 15 点伤害', '/images/cards/销售_Amy.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-38');
UPDATE `cards` SET `card_name` = 'Amy', `description` = '立即造成 15 点伤害', `card_type` = 'attack', `cost` = 3, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Amy.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'S-38';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-38';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 15, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-38';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 206, 'S-39', 'Kade', 1, 'sales', 0, 'attack', '立即造成 2 点伤害，并为自己增加 3 点防御', '/images/cards/销售_Kade.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-39');
UPDATE `cards` SET `card_name` = 'Kade', `description` = '立即造成 2 点伤害，并为自己增加 3 点防御', `card_type` = 'attack', `cost` = 0, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Kade.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'S-39';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-39';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-39';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-39';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 207, 'S-40', 'Felicity', 1, 'sales', 1, 'attack', '立即造成 3 点伤害，并为自己增加 4 点防御', '/images/cards/销售_Felicity.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-40');
UPDATE `cards` SET `card_name` = 'Felicity', `description` = '立即造成 3 点伤害，并为自己增加 4 点防御', `card_type` = 'attack', `cost` = 1, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Felicity.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'S-40';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-40';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 3, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-40';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-40';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 208, 'S-41', 'Riley', 1, 'sales', 2, 'attack', '立即造成 7 点伤害，并为自己增加 9 点防御', '/images/cards/销售_Riley.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-41');
UPDATE `cards` SET `card_name` = 'Riley', `description` = '立即造成 7 点伤害，并为自己增加 9 点防御', `card_type` = 'attack', `cost` = 2, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Riley.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'S-41';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-41';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 7, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-41';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 9, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-41';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 209, 'S-42', 'Daniel', 1, 'sales', 3, 'attack', '立即造成 12 点伤害，并为自己增加 15 点防御', '/images/cards/销售_Daniel.webp', NULL, 0, 0, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-42');
UPDATE `cards` SET `card_name` = 'Daniel', `description` = '立即造成 12 点伤害，并为自己增加 15 点防御', `card_type` = 'attack', `cost` = 3, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Daniel.webp', `require_unlock` = 0, `status` = 1 WHERE `card_code` = 'S-42';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-42';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 12, 'BOSS', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-42';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'SELF', 'ADD_SHIELD', 'IMMEDIATE', 0, 1, 'STACK', 0, 15, 'SELF', NULL, NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-42';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 210, 'S-43', 'Kinyond', 1, 'sales', 3, 'attack', '50% 概率立即造成 30 点伤害', '/images/cards/销售_Kinyond.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'S-43');
UPDATE `cards` SET `card_name` = 'Kinyond', `description` = '50% 概率立即造成 30 点伤害', `card_type` = 'attack', `cost` = 3, `dept_id` = 1, `dept_type` = 'sales', `image_url` = '/images/cards/销售_Kinyond.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'S-43';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'S-43';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 30, 'BOSS', '{"chance":50}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'S-43';

ALTER TABLE `cards` AUTO_INCREMENT = 211;
