-- 公共部设计部文艺射手成员卡（穿透伤害）。可重复执行。不覆盖已有销售/采购/营销卡面。
-- id 237–241：接在 MK-04（236）之后。玩法部门为公共部；卡面文件名用「设计部_」前缀，图鉴显示设计部。
-- 必须在 018、028、031、032 之后执行，否则会被 018 停用。
INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 237, 'DS-01', 'Tancy', 3, 'public', 0, 'attack', '对霸凌者造成 1 点穿透伤害（无视护盾）', '/images/cards/设计部_Tancy.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'DS-01');
UPDATE `cards` SET `card_name` = 'Tancy', `description` = '对霸凌者造成 1 点穿透伤害（无视护盾）', `card_type` = 'attack', `cost` = 0, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/设计部_Tancy.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'DS-01';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'DS-01';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'DS-01';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 238, 'DS-02', 'Nico', 3, 'public', 1, 'attack', '对霸凌者造成 2 点穿透伤害（无视护盾）', '/images/cards/设计部_Nico.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'DS-02');
UPDATE `cards` SET `card_name` = 'Nico', `description` = '对霸凌者造成 2 点穿透伤害（无视护盾）', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/设计部_Nico.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'DS-02';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'DS-02';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 2, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'DS-02';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 239, 'DS-03', 'Harrison', 3, 'public', 2, 'attack', '对霸凌者造成 4 点穿透伤害（无视护盾）', '/images/cards/设计部_Harrison.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'DS-03');
UPDATE `cards` SET `card_name` = 'Harrison', `description` = '对霸凌者造成 4 点穿透伤害（无视护盾）', `card_type` = 'attack', `cost` = 2, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/设计部_Harrison.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'DS-03';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'DS-03';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 4, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'DS-03';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 240, 'DS-04', 'Leo', 3, 'public', 3, 'attack', '对霸凌者造成 6 点穿透伤害（无视护盾）', '/images/cards/设计部_Leo.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'DS-04');
UPDATE `cards` SET `card_name` = 'Leo', `description` = '对霸凌者造成 6 点穿透伤害（无视护盾）', `card_type` = 'attack', `cost` = 3, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/设计部_Leo.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'DS-04';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'DS-04';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 6, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'DS-04';

INSERT INTO `cards` (`id`,`card_code`,`card_name`,`dept_id`,`dept_type`,`cost`,`card_type`,`description`,`image_url`,`combo_card_id`,`is_unique`,`require_unlock`,`status`,`created_at`,`updated_at`) SELECT 241, 'DS-05', 'Yuna', 3, 'public', 1, 'attack', '对霸凌者造成 1 点穿透伤害，持续 3 回合（含本回合）', '/images/cards/设计部_Yuna.webp', NULL, 0, 1, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cards` WHERE `card_code` = 'DS-05');
UPDATE `cards` SET `card_name` = 'Yuna', `description` = '对霸凌者造成 1 点穿透伤害，持续 3 回合（含本回合）', `card_type` = 'attack', `cost` = 1, `dept_id` = 3, `dept_type` = 'public', `image_url` = '/images/cards/设计部_Yuna.webp', `require_unlock` = 1, `status` = 1 WHERE `card_code` = 'DS-05';
DELETE e FROM `card_effects` e INNER JOIN `cards` c ON c.id = e.card_id WHERE c.card_code = 'DS-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 1, 'BOSS', 'DAMAGE_BOSS', 'IMMEDIATE', 0, 1, 'STACK', 0, 1, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'DS-05';
INSERT INTO `card_effects` (`card_id`,`effect_order`,`effect_scope`,`effect_type`,`trigger_timing`,`trigger_delay`,`remaining_triggers`,`stack_rule`,`duration_rounds`,`value`,`target_rule`,`extra_data`,`created_at`,`updated_at`) SELECT c.id, 2, 'BOSS', 'DAMAGE_BOSS', 'ROUND_START', 1, 2, 'STACK', 2, 1, 'BOSS', '{"ignoreShield":true}', NOW(), NOW() FROM `cards` c WHERE c.card_code = 'DS-05';

ALTER TABLE `cards` AUTO_INCREMENT = 242;
